### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/sowm#1]
- [x] Pointer follows focus.
- [x] Fix sending a window to another workspace.
- [x] Fullscreen toggle.
- [x] Center window.
- [ ] Rounded corners.
- [ ] A whole lotta clean up.

**Comment by onodera-punpun** [comment]
You could do (probably more beautiful, since they are smoothed) rounded corners with https://github.com/yshui/compton/pull/229

**Comment by dylanaraps** [comment]
I don't use a compositor but I'm lucky in that I have a HiDPI display. I can't see the pixels of the non-AA rounded corners at all. I've got a few patches to cherry pick ideas from so this should be interesting.

**Comment by dylanaraps** [comment]
Rounded corners will remain a patch in this repository regardless. :)

**Comment by dylanaraps** [comment]
![sowm](https://user-images.githubusercontent.com/6799467/66687576-9747c200-ec72-11e9-947d-5b96753eab03.jpg)

**Comment by lucat1** [comment]
Are rounded corners still coming, or did you give up?

**Comment by dylanaraps** [comment]
Behold: https://github.com/dylanaraps/sowm/pull/4

**Comment by dylanaraps** [comment]
Rounded corners now lives here in a patch: https://github.com/dylanaraps/sowm/blob/master/patches/sowm-rounded-corners.patch
